name: Build and Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Bundle
        run: npm run bundle

      - name: Build project for macOS and Windows
        run: npm run build

      - name: Compress macOS binary
        run: tar -czvf ./bin/airdrop-mac.tar.gz -C ./bin airdrop

      - name: Compress Windows binary
        run: zip -j ./bin/airdrop-win.zip ./bin/airdrop.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: 'Here is the new release of Airdrop.'

      - name: Upload macOS binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/airdrop-mac.tar.gz
          asset_name: airdrop-mac.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/airdrop-win.zip
          asset_name: airdrop-win.zip
          asset_content_type: application/zip
